### ISSUE TITLE
Can't get json & xml to work

### ISSUE THREAD

**Issue by mathieugagne** [matiaskorhonen/brewtoad-export#1]
1st off, thanks for sharing a solution we all need.

I get a 403 Forbidden error page in json and xml files.

I've tried:
- [x] Running the script as is
- [x] Adding a step to login using puppeteer.
```
await page.goto("https://www.brewtoad.com/accounts/sign_in")
await page.type("#user_login", "xxx")
await page.type("#user_password", "xxx")
await Promise.all([
  page.waitForNavigation({waitUntil: 'load', timeout: 0}),
  page.click("input[type=submit]"),
])
```
- [x] Setting my auth cookie
```
await page.setCookie({
  "value": "xxx",
  "domain": "brewtoad.com",
  "name": "_brewed_session"
})
```

Any help would be appreciated. I could carry on but you seem to have it working for yourself.

**Comment by matiaskorhonen** [comment]
It's probably because the script doesn't fetch the JSON and XML via Chrome but uses Node's HTTP library directly.

You should be able to circumvent this by signing in with chrome, then [reading the session cookie from Puppeteer](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#pagecookiesurls) and then you can use the cookie with the XML/JSON requests (e.g. https://stackoverflow.com/a/23056332/1439994).

I suppose it would also be possible to use Puppeteer to fetch the XML or JSON but I'm not sure how that would work.

Personally I got away without authentication since all my recipes are/were public. If you get this to work, I'd be glad to accept a PR…

**Comment by matiaskorhonen** [comment]
I actually ended up fixing this myself. Just pull the latest version (d42ac02f746c006c3ca610c826f48c299149b699)…

**Comment by matiaskorhonen** [comment]
I also updated the README to take these changes into account: https://github.com/matiaskorhonen/brewtoad-export#readme
